steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install','-f','spring-boot-gcp-poc/pom.xml','-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','spring-boot-gcp-poc/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/gcp-test', '.']
images: ['gcr.io/$PROJECT_ID/gcp-test']

