steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package','-f','spring-boot-gcp-poc','-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','spring-boot-gcp-poc', '-t', 'gcr.io/$PROJECT_ID/gcp-test', '.']
images: ['gcr.io/$PROJECT_ID/gcp-test']

